# Config file for automatic testing at travis-ci.org
# This file will be regenerated if you run travis_pypi_setup.py

language: python

env:
  - TOXENV=py34
  - TOXENV=flake8
  - TOXENV=isort
  - TOXENV=manifest
  - TOXENV=docs
  - TOXENV=pep257

before_install:
  - pip install codecov

before-script:
  - psql -U postgres -c "CREATE USER dsa-merchant WITH CREATEUSER PASSWORD 'dsa-merchant';"
  - psql -U postgres -c "ALTER USER  dsa-merchant CREATEDB;"

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - pip install -U tox codecov

# command to run tests, e.g. python setup.py test
script:
  - psql -U postgres -c "CREATE USER  dsa-merchant WITH CREATEUSER PASSWORD 'foobar';"
  - psql -U postgres -c "ALTER USER  dsa-merchant CREATEDB;"
  - make test-all

after_success:
  - codecov
